### ISSUE TITLE
Make an option for the summaries to appear as a thread reply so they don't interrupt the conversation flow

### ISSUE THREAD

**Issue by moodler** [openedtech/edubot-matrix#10]
Make an option for the summaries to appear as a thread reply so they don't interrupt the conversation flow

**Comment by exciteabletom** [comment]
As we we're currently ignoring thread replies to keep database schema and chronology simple, this may cause problems.

The thread reply won't be saved into the database, and the bot won't react to replies of it's summary.

**Comment by moodler** [comment]
Why can't you also still push it into the history?  You're making the comment so you're in control.  Replies in threads can still be ignored as they are now.
