### ISSUE TITLE
Make the spontaneous interjections adjustable per room

### ISSUE THREAD

**Issue by moodler** [openedtech/edubot-matrix#9]
Sometimes the bot gets noisy, interjecting too much into the discussions.  
It would be nice to be able to turn it down in that room or turn it up.

!moodlebot interject 0-50 

0 = don't interject ever (it will still reply when directly addressed) 
1 = interject after every message 
50 = interject after approximately every 50 messages

**Comment by exciteabletom** [comment]
Closed in a550c5787bb4ae97b64951b76819eff0024c1225
